// Ganchos de capa testaveis: 5 por tema de dicas (GANCHOS) e por historinha (GANCHOS_HISTORIA). Criado no loop de 10/10/2026.
// Uso: volta = Math.floor(doAno / TEMAS.length) % 5 -> GANCHOS[tema.id][volta].

export const GANCHOS = {
  'primeiro-mes': [
    'Primeiro mês com bebê: 4 coisas que alguém precisava ter te dito',
    'Ninguém te avisa disso no primeiro mês (e devia)',
    'Se você acha que está errando tudo no primeiro mês, lê isso',
    'O primeiro mês não é como no Instagram. 4 verdades',
    'Manda pra amiga que acabou de ter bebê',
  ],
  'sono-seguro': [
    'O berço mais seguro é o mais sem graça',
    'Travesseiro, protetor e naninha: por que ficam fora do berço',
    'O berço lindo do Pinterest não é o berço seguro',
    'Barriga pra cima e mais 3 regras do sono seguro (SBP)',
    'Manda pra avó antes de ela montar o berço',
  ],
  banho: [
    'O banho do bebê tem 1 regra que não pode quebrar',
    'Nem pra pegar a toalha: a regra do banho do bebê',
    'O erro do banho que acontece em segundos',
    'Água a 36 °C e mais 3 coisas pro banho dar certo',
    'Manda pra quem dá banho no seu bebê também',
  ],
  visitas: [
    'Manda pra família antes do bebê nascer: as 4 regras da visita',
    '“Só um beijinho no rosto”: por que não',
    'Colocar limite na visita não é falta de educação',
    'Visita boa não fica 3 horas. Fica e lava a louça',
    'Manda no grupo da família: as regras da visita',
  ],
  autocuidado: [
    'Você bebeu água hoje? 4 cuidados que cabem no cochilo do bebê',
    'Quando foi seu último banho sem pressa?',
    'Mãe com fome fica sem paciência. E tudo bem admitir',
    'Cuidar de você também é cuidar do bebê. 4 jeitos rápidos',
    'Manda pra uma mãe que esqueceu dela mesma',
  ],
  'enxoval-esperto': [
    'Não compre muita roupa RN. E mais 3 verdades do enxoval',
    'O tamanho RN dura bem menos do que você imagina',
    'O erro de enxoval que quase toda mãe de primeira viagem comete',
    'Enxoval não precisa ser enorme. Precisa ser útil',
    'Manda pra amiga grávida antes de ela ir às compras',
  ],
  rotina: [
    'Fralda em cada canto da casa e mais 3 truques de rotina',
    'A manhã com bebê começa na noite anterior',
    'Rotina com bebê desandando? Começa por aqui',
    'Revezar a madrugada muda tudo. E mais 3 truques',
    'Salva pra testar essa semana: 4 truques de rotina',
  ],
  frases: [
    'Se o seu dia foi difícil, lê isso antes de dormir',
    'Dá pra amar o filho e não amar a fase',
    'Você está fazendo o seu melhor. E é suficiente',
    '4 frases que toda mãe precisava ouvir hoje',
    'Manda pra uma mãe que precisa ler isso hoje',
  ],
  passeio: [
    'Primeiro passeio com o bebê? Printa isso antes de sair',
    'O que levar no primeiro passeio (e o que todo mundo esquece)',
    'Sol forte e bebê pequeno não combinam. O checklist do passeio',
    'Bebê usa uma camada a mais que você. E mais 3 dicas',
    'Salva: você vai precisar no dia do primeiro passeio',
  ],
  parceiro: [
    'Pai não ajuda. Pai divide. (4 coisas que são dele também)',
    '“Ele me ajuda muito”: por que essa frase está errada',
    'Ninguém ajuda a cuidar do próprio filho',
    '4 coisas que são do pai também',
    'Manda pro pai do seu bebê. Sem indireta 😉',
  ],
  quarto: [
    'O quarto que salva a madrugada não é o do Pinterest',
    'Trocador na altura errada: o erro que você sente nas costas',
    'Quarto bonito ou quarto prático? A madrugada responde',
    '4 detalhes do quarto do bebê que salvam as suas costas',
    'Salva antes de montar o quarto do bebê',
  ],
  choro: [
    'Bebê chorando e você já tentou de tudo? Confere nessa ordem',
    'O choro do bebê tem uma ordem pra checar',
    'Às vezes não é fome. Às vezes é só colo',
    'Colo não estraga bebê. E mais 3 coisas sobre o choro',
    'Salva pra madrugada: a ordem do choro',
  ],
  cadeirinha: [
    'A lei deixa virar a cadeirinha cedo. Pediatras pedem mais tempo',
    'Bebê de costas no carro: por que pediatras pedem mais tempo',
    'Casaco grosso na cadeirinha: o erro que quase ninguém sabe',
    'Vire a cadeirinha pelo manual, não pela idade',
    'Manda pra quem leva o seu bebê de carro',
  ],
  andador: [
    'O item de bebê que os pediatras pedem pra não usar',
    'Andador não ensina a andar. E tem um risco que pouca gente sabe',
    'Antes de dar andador de presente, lê isso',
    'Por que a Sociedade Brasileira de Pediatria é contra o andador',
    'Manda pra quem ia dar um andador pro seu bebê',
  ],
  'prato-do-bebe': [
    '4 coisas fora do prato do bebê (nem com a vó insistindo)',
    '“Só um pouquinho de mel não faz mal.” Faz, sim',
    'O que a vó oferece e o Ministério da Saúde pede pra esperar',
    'Zero açúcar até os 2 anos. E mais 3 regras do prato do bebê',
    'Manda pra vó antes do próximo almoço de domingo',
  ],
  engasgo: [
    'Uva inteira não é comida de criança pequena. Corta assim',
    'Engasgo pode não fazer barulho nenhum',
    'O jeito certo de cortar uva pra criança pequena',
    'Comer andando, correndo ou no carro: por que não',
    'Manda pra babá ou pra creche: o corte que evita engasgo',
  ],
  telas: [
    'Zero tela antes dos 2 anos. E quando você precisa de 10 minutos?',
    'TV ligada de fundo também conta como tela',
    'O que fazer com o bebê enquanto você cozinha (sem tela)',
    'Colher de pau e pote: o “brinquedo” que segura o bebê',
    'Menos tela sem culpa: salva essas 4 ideias',
  ],
  'mala-maternidade': [
    'Mala da maternidade: printa esse checklist',
    'O que levar pra maternidade (e o que quase todo mundo esquece)',
    'Grávida? Salva esse checklist da mala',
    'A mala do acompanhante também conta',
    'Manda pra amiga que tá no 3º trimestre',
  ],
  'frases-ouvidas': [
    '“Esse leite é fraco” e mais 3 frases que toda mãe ouve',
    '“Colo vicia”: o que responder',
    'Frases que toda mãe já ouviu (e o que responder com carinho)',
    '“Dá um chazinho”: por que não antes dos 6 meses',
    'Manda pra quem vive dando esses palpites 😅',
  ],
  'carga-mental': [
    'Ninguém vê esse trabalho. Manda pro pai do seu bebê',
    'Cansada sem ter “feito nada”? É isso aqui',
    'O trabalho da mãe que não aparece em foto',
    'Dividir não é esperar ela pedir',
    'Lembrar da vacina também é trabalho. Manda pra ele',
  ],
  puerperio: [
    'Quando o cansaço do pós-parto não é só cansaço',
    'Baby blues ou algo mais? Os sinais pra prestar atenção',
    'Tristeza que não passa depois do parto não é frescura',
    'Você não precisa passar pelo pós-parto sozinha',
    'Manda pra amiga que acabou de ter bebê',
  ],
  caderneta: [
    'A Caderneta da Criança tem páginas que quase ninguém usa',
    'Você sabe ler o gráfico da caderneta do seu bebê?',
    'O documento que vai em toda consulta (e quase ninguém lê)',
    '4 coisas da caderneta que ajudam a acompanhar o seu bebê',
    'Salva e leva a caderneta na próxima consulta',
  ],
  'brincar-0-6': [
    'Bebê de 0 a 6 meses não precisa de brinquedo caro. Precisa disso',
    'O melhor brinquedo do bebê é o seu rosto',
    'Barriguinha pra baixo: quando, como e por quê',
    '4 brincadeiras de graça pra bebê de 0 a 6 meses',
    'Manda pra quem fica com o bebê durante o dia',
  ],
  'febre-anota': [
    'Bebê com febre: anota isso antes de ligar pro pediatra',
    'O que o pediatra vai perguntar quando o bebê tiver febre',
    'Febre em bebê com menos de 3 meses: não espere',
    '4 coisas pra anotar quando o bebê tem febre',
    'Salva pra hora do aperto: o que anotar na febre',
  ],
};

// Historinhas (achados): 5 pares [gancho, sub] por historia. O 1o e o de historia-novo.mjs.
export const GANCHOS_HISTORIA = {
  'enxoval-caro': [
    ['Enxoval não precisa custar um salário', 'arrasta: 3 coisas que toda mãe usa'],
    ['Enxoval de rica com salário de CLT', 'dá, sim (arrasta)'],
    ['O enxoval que cabe no mês', '3 coisas que toda mãe usa'],
    ['Antes de pagar preço cheio no enxoval, olha isso', '3 coisas do dia a dia'],
    ['Manda pra amiga que tá montando o enxoval', '3 coisas que ela vai usar'],
  ],
  'cresce-rapido': [
    ['Bebê cresce tão rápido que tem roupa que nem chega a ser usada', 'por isso não vale pagar caro'],
    ['Ontem servia. Hoje não fecha mais', 'bebê cresce rápido demais'],
    ['O body que não fecha mais: toda mãe já viveu isso', 'por isso não vale pagar caro'],
    ['Roupa de bebê dura semanas, não meses', 'arrasta antes de pagar caro'],
    ['Qual roupinha seu bebê perdeu sem nem usar?', 'arrasta'],
  ],
  madrugada: [
    ['3 da manhã, bebê chorando. Você tem tudo à mão?', 'confere essas 3 coisas'],
    ['A madrugada com bebê já é difícil', 'não deixa faltar isso'],
    ['O que você vai querer ter perto às 3 da manhã', 'arrasta e confere'],
    ['Deixa isso pronto antes de dormir', 'a madrugada agradece'],
    ['Manda pra quem tá na fase das madrugadas', '3 coisas que salvam'],
  ],
  'lista-cha': [
    ['O que ninguém coloca na lista do chá de bebê', 'mas você vai usar todo dia'],
    ['A lista do chá de bebê esqueceu isso', 'e você vai usar todo dia'],
    ['Montando a lista do chá? Coloca isso', 'ninguém lembra'],
    ['3 itens que somem da lista do chá (e fazem falta)', 'arrasta'],
    ['Manda pra quem tá montando a lista do chá', '3 coisas que ninguém lembra'],
  ],
  'primeira-vez': [
    ['O erro de enxoval mais comum: comprar tudo antes de nascer', 'dá pra ir comprando aos poucos'],
    ['Não compre tudo antes de o bebê nascer', 'ele te mostra do que precisa'],
    ['O enxoval de verdade se monta depois do parto', 'arrasta'],
    ['Comprou tudo antes de nascer? Toda mãe faz isso', 'dá pra fazer diferente'],
    ['Manda pra amiga grávida antes de ela ir às compras', 'compra aos poucos'],
  ],
  respiro: [
    ['Parece bobagem até você virar mãe', 'arrasta e diz se não é verdade'],
    ['“Eu não preciso disso”: toda mãe já disse antes do bebê', 'arrasta'],
    ['Coisa pequena que salva o dia', 'arrasta pra ver'],
    ['Antes de ser mãe: bobagem. Depois: essencial', 'arrasta'],
    ['Manda pra amiga que vai ser mãe', 'ela vai entender depois'],
  ],
};
